### ISSUE TITLE
Add ON Semi logo to website - Gigawatt

### ISSUE THREAD

**Issue by ay1741** [RIT-EVT/RIT-EVT.github.io#114]
Logos are here:  https://drive.google.com/drive/u/0/folders/15d1MB1ZS27ZoMfm5FQgBIGh6WJfFZrpc

**Comment by RyanThorna** [comment]
Added the logo to Gigawatt. Will close issue when website is deployed.

**Comment by RyanThorna** [comment]
Complete.
