### ISSUE TITLE
Add Magna International to sponsors

### ISSUE THREAD

**Issue by ay1741** [RIT-EVT/RIT-EVT.github.io#120]
They donated $1000 and need a logo on our Megawatt tier.

Logos are located here: https://drive.google.com/drive/u/1/folders/1wPZNjmaJQhDm-WSjEeiKVvSX6A59wa_l

**Comment by rwfitri** [comment]
I couldn't see your link

**Comment by ay1741** [comment]
@RyanThorna Is this your account? Message me on slack directly if it is, otherwise, I will block the user.

**Comment by RyanThorna** [comment]
This is me. I'm not sure who @rwfitri is.

**Comment by rwfitri** [comment]
Sorry why u have to block my account?
