### ISSUE TITLE
Update Officer pictures

### ISSUE THREAD

**Issue by ay1741** [RIT-EVT/RIT-EVT.github.io#146]
Need to get them old folks out of here, new pics below:

![zach](https://user-images.githubusercontent.com/1278691/47933204-451af000-deaa-11e8-9cb5-a4bad2eefd5e.png)
![larissa](https://user-images.githubusercontent.com/1278691/47933215-4fd58500-deaa-11e8-814d-47fc5389f192.png)
![john_](https://user-images.githubusercontent.com/1278691/47933220-57952980-deaa-11e8-9ec9-cc6f028f53fd.png)
![garrett](https://user-images.githubusercontent.com/1278691/47933223-5b28b080-deaa-11e8-85e2-d803cf0511d7.png)
![dan](https://user-images.githubusercontent.com/1278691/47933228-6085fb00-deaa-11e8-9587-a8e364c84702.png)
![andrew](https://user-images.githubusercontent.com/1278691/47933234-64198200-deaa-11e8-9846-31b03f6aa181.png)

**Comment by bxc3247** [comment]
Website has been updated for the new Officers.
