### ISSUE TITLE
This is a list of ideas

### ISSUE THREAD

**Issue by derekkg** [RIT-EVT/RIT-EVT.github.io#17]
These are just suggestions and ideas that I had when looking at the site.

- The title text in the tab of my browser just says "home" on the homepage of evt. Perhaps it should say RIT ELectric Vehicle Team? Or something more descriptive.

- Issue with low resolution screens: On my chromebook the bottom of the meeting time is cut off, even at default zoom. It isn't if I make it narrower though.
![screenshot 2015-02-20 at 1 12 45 pm](https://cloud.githubusercontent.com/assets/6548903/6306523/3146eb8c-b902-11e4-8bd5-700a8b0f83c6.png)

**Comment by jcdesimp** [comment]
@derekkg The title would be a really quick fix, we wold have to play around with out scaling and responsiveness to see what the issue with the lower resolution displays are, definitely something we should fix though.

**Comment by derekkg** [comment]
Oh, Also, the favicon is only on the home page

**Comment by jcdesimp** [comment]
Favicon issue should be resolved with issue #15 

Title issue has been fixed.
