### ISSUE TITLE
Make a members page?

### ISSUE THREAD

**Issue by derekkg2** [RIT-EVT/RIT-EVT.github.io#20]
Idea - maybe make a page with member specific resources. Links to the wiki, jira, bitbucket, github, jenkins, etc. Email updates could be posted here also if people miss some.

-Geoff

**Comment by derekkg2** [comment]
Oh, also maybe put link to swipe access form on this page. Make sure it doesn't get spammed. Google can probably handle this.

-Geoff

**Comment by derekkg2** [comment]
Also, put a robots.txt in the directory for this page to stop Google from indexing it

**Comment by jcdesimp** [comment]
@derekkg why don't we want google indexing it?

**Comment by sidewinder12s** [comment]
Might help cut down on spam to the links that we would put in the members resources page.

**Comment by derekkg** [comment]
I think the fileshare link goes to the wrong page. I believe this is the one we would want to send people to.
https://wiki.rit.edu/display/EVT/How+to+connect+to+EVT-Share
