### ISSUE TITLE
Add link to Slack signup

### ISSUE THREAD

**Issue by benkantor** [RIT-EVT/RIT-EVT.github.io#41]

**Comment by jcdesimp** [comment]
We finally got a slack?

**Comment by sidewinder12s** [comment]
https://ritevt.slack.com/

On Sunday, September 13, 2015, Joseph DeSimpliciis <notifications@github.com>
wrote:

> We finally got a slack?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RIT-EVT/RIT-EVT.github.io/issues/41#issuecomment-139845562>
> .
>


-- 

Geoffrey Webster
c. 810-623-9540
e. gow4272@rit.edu
B. S. Applied Networking & System Administration '15
Rochester Institute of Technology
