### ISSUE TITLE
Update Sponsorship Page

### ISSUE THREAD

**Issue by RyanThorna** [RIT-EVT/RIT-EVT.github.io#51]
Need a logo and link for Altium (Gigawatt level) and one for Keysight Technologies (Gigawatt level). I will put the Altium logo on the file share in Z:\Documents\Sponsorship\Altium.

**Comment by derekkg** [comment]
[Altium+keysight.zip](https://github.com/RIT-EVT/RIT-EVT.github.io/files/149521/Altium.keysight.zip)
Files
